sudo: false

language: perl

perl:
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

before_install:
  - cpanm --notest
    Devel::Cover::Report::Coveralls

script:
  - cover -test -report coveralls
  - perl Makefile.PL
  - make 3rd
  - make test

