name: mojo-soap-tests

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'    

jobs:

  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-16.04,ubuntu-18.04]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v1

    - name: build and test
      run: |
        perl Makefile.PL
        make 3rd
        make test