name: mojo-soap-tests

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'    

jobs:

  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-16.04,ubuntu-18.04]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache
      id: cpan-cache
      uses: actions/cache@v1
      with:
        path: ~/3rd
        key: ${{ runner.os }}-cpan-${{ hashFiles(Makefile.PL) }}
        
    - name: Prepare
      run: perl Makefile.PL
    
    - name: Make 3rd Party
      if: steps.cpan-cache.outputs.cache-hit != 'true'
      run: make 3rd
 
    - name: Run Tests
      run: make test